### ISSUE TITLE
Prueba Jekyll

### ISSUE THREAD

**Issue by CarlosGS** [UC3Music/UC3Music.github.io#1]
Hey David, me he encontrado con éste repo de casualidad en el "home" de github.
Te recomiendo que pruebes [Jekyll](http://jekyllrb.com/), funciona fenomenal y es mucho más cómodo que los generadores de GitHub pages.

Si quieres usa la web de nuestro club de robótica como plantilla:
https://github.com/CRM-UAM/CRM-UAM.github.io

Salu2!!

**Comment by David-Estevez** [comment]
Hola Carlos!!

Acabo de crear la página un poco como prueba, y no había conseguido todavía ver la página por defecto (ha tardad un poco en dejar de darme el error 404 y mostrarme la web). Como estoy en el curro, he preferido dejarlo ahí, pero echaré un ojo a vuestra página cuando llegue a casa. 

Jekyll lo he llegado a usar de forma interna en mi pc en casa, le echaré un ojo también como GitHub page. La idea era crear una "home" con todos los proyectos, y que cada proyecto tuviese su propia GitHub page y/o wiki. Más adelante podemos redirigir desde uc3music.uc3m.es si queremos una url más..."corporativa"/"oficial".

Me alegro de tener noticias tuyas, a ver si nos vemos pronto! Y muchas gracias por pasarme el link, seguro que me será de ayuda para enterarme de cómo funciona todo esto!! :smile:

**Comment by CarlosGS** [comment]
Ok, si es sólo una sugerencia. Me encanta cómo tenéis todo lo de la asociación en un repo, a ver si podemos hacer lo mismo en el club de robótica :D
Y sí, espero que nos veamos pronto, a ver si me dejan pasarme por allí ^^
